### ISSUE TITLE
Describe IBM Watson Tone Analyzer

### ISSUE THREAD

**Issue by MexsonFernandes** [MexsonFernandes/Emotion-Controlled-Robot-using-IBM-Watson-Tone-Analyzer#1]
Help new comers to know about IBM Tone analyzer.

**Comment by zMrKrabz** [comment]
Mind if I take a shot at this? And do you just want me to improve the readme by adding a description of this project?

**Comment by MexsonFernandes** [comment]
Add a description and some screenshots. You will find in poster.pdf or poster.pptx file. Also add some badges. @zMrKrabz
